# These are supported funding model platforms

custom: https://deinserverhost.de/store/aff.php?aff=4224 # Affiliate program from our hoster, if you buy a product from [DeinServerHost](https://deinserverhost.de/store/aff.php?aff=4224) we get a small commission. But this costs you **NONE** cent more. :)
